version: "2"
services:

  pyrrha_boxplorer:
    container_name: "pyrrha_boxplorer"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_BOXPROXY_PROTOCOL=http
        - REACT_APP_BOXPROXY_HOST=boxproxy.staging.pandora.network
        - REACT_APP_BOXPROXY_PORT=80
        - REACT_APP_BOXPROXY_WS_PORT=1337
    volumes:
      - "./.logs:/logs"
    ports:
      - "8080:8080"
    networks: 
      pyrrha:
        aliases:
          - pyrrha_boxplorer    

networks: 
  pyrrha:
